package com.gusanitolabs.rovia.core.designsystem

import androidx.compose.ui.graphics.Color

internal val RoviaBackground = Color(0xFFF9F9F9)
internal val RoviaError = Color(0xFFBA1A1A)
internal val RoviaErrorContainer = Color(0xFFFFDAD6)
internal val RoviaInverseOnSurface = Color(0xFFF0F1F1)
internal val RoviaInversePrimary = Color(0xFFDAC1BC)
internal val RoviaInverseSurface = Color(0xFF2F3131)
internal val RoviaOnBackground = Color(0xFF1A1C1C)
internal val RoviaOnError = Color(0xFFFFFFFF)
internal val RoviaOnErrorContainer = Color(0xFF93000A)
internal val RoviaOnPrimary = Color(0xFFFFFFFF)
internal val RoviaOnPrimaryContainer = Color(0xFFA08A85)
internal val RoviaOnSecondary = Color(0xFFFFFFFF)
internal val RoviaOnSecondaryContainer = Color(0xFF6F6051)
internal val RoviaOnSurface = Color(0xFF1A1C1C)
internal val RoviaOnSurfaceVariant = Color(0xFF4F4442)
internal val RoviaOnTertiary = Color(0xFFFFFFFF)
internal val RoviaOnTertiaryContainer = Color(0xFFC37F50)
internal val RoviaOutline = Color(0xFF817472)
internal val RoviaOutlineVariant = Color(0xFFD2C3C0)
internal val RoviaPrimary = Color(0xFF1D100D)
internal val RoviaPrimaryContainer = Color(0xFF332421)
internal val RoviaScrim = Color(0xFF000000)
internal val RoviaSecondary = Color(0xFF6B5C4D)
internal val RoviaSecondaryContainer = Color(0xFFF1DCC9)
internal val RoviaSurface = Color(0xFFF9F9F9)
internal val RoviaSurfaceBright = Color(0xFFF9F9F9)
internal val RoviaSurfaceContainer = Color(0xFFEEEEEE)
internal val RoviaSurfaceContainerHigh = Color(0xFFE8E8E8)
internal val RoviaSurfaceContainerHighest = Color(0xFFE2E2E2)
internal val RoviaSurfaceContainerLow = Color(0xFFF3F3F4)
internal val RoviaSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val RoviaSurfaceDim = Color(0xFFDADADA)
internal val RoviaSurfaceTint = Color(0xFF6D5A56)
internal val RoviaSurfaceVariant = Color(0xFFE2E2E2)
internal val RoviaTertiary = Color(0xFF240D00)
internal val RoviaTertiaryContainer = Color(0xFF431D00)
