package com.gusanitolabs.robia.core.designsystem

import androidx.compose.ui.graphics.Color

internal val RobiaBackground = Color(0xFFF9F9F9)
internal val RobiaError = Color(0xFFBA1A1A)
internal val RobiaErrorContainer = Color(0xFFFFDAD6)
internal val RobiaInverseOnSurface = Color(0xFFF0F1F1)
internal val RobiaInversePrimary = Color(0xFFDAC1BC)
internal val RobiaInverseSurface = Color(0xFF2F3131)
internal val RobiaOnBackground = Color(0xFF1A1C1C)
internal val RobiaOnError = Color(0xFFFFFFFF)
internal val RobiaOnErrorContainer = Color(0xFF93000A)
internal val RobiaOnPrimary = Color(0xFFFFFFFF)
internal val RobiaOnPrimaryContainer = Color(0xFFA08A85)
internal val RobiaOnSecondary = Color(0xFFFFFFFF)
internal val RobiaOnSecondaryContainer = Color(0xFF6F6051)
internal val RobiaOnSurface = Color(0xFF1A1C1C)
internal val RobiaOnSurfaceVariant = Color(0xFF4F4442)
internal val RobiaOnTertiary = Color(0xFFFFFFFF)
internal val RobiaOnTertiaryContainer = Color(0xFFC37F50)
internal val RobiaOutline = Color(0xFF817472)
internal val RobiaOutlineVariant = Color(0xFFD2C3C0)
internal val RobiaPrimary = Color(0xFF1D100D)
internal val RobiaPrimaryContainer = Color(0xFF332421)
internal val RobiaScrim = Color(0xFF000000)
internal val RobiaSecondary = Color(0xFF6B5C4D)
internal val RobiaSecondaryContainer = Color(0xFFF1DCC9)
internal val RobiaSurface = Color(0xFFF9F9F9)
internal val RobiaSurfaceBright = Color(0xFFF9F9F9)
internal val RobiaSurfaceContainer = Color(0xFFEEEEEE)
internal val RobiaSurfaceContainerHigh = Color(0xFFE8E8E8)
internal val RobiaSurfaceContainerHighest = Color(0xFFE2E2E2)
internal val RobiaSurfaceContainerLow = Color(0xFFF3F3F4)
internal val RobiaSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val RobiaSurfaceDim = Color(0xFFDADADA)
internal val RobiaSurfaceTint = Color(0xFF6D5A56)
internal val RobiaSurfaceVariant = Color(0xFFE2E2E2)
internal val RobiaTertiary = Color(0xFF240D00)
internal val RobiaTertiaryContainer = Color(0xFF431D00)
